apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ag9m54c59-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ag9m54c59-dotnet-basic-gitops